export enum ACTION {
  LOGGING_USER = "LOGGING_USER",
  LOGOUT_USER = "LOGOUT_USER",
  RECEIVE_USER = "RECEIVE_USER",
  RECEIVE_QUESTIONS = "RECEIVE_QUESTIONS",
  ADD_QUESTION = "ADD_QUESTION",
  SAVE_QUESTION_ANSWER = "SAVE_QUESTION_ANSWER",
  SAVE_USER_ANSWER = "SAVE_USER_ANSWER",
  ADD_USER_QUESTION = "ADD_USER_QUESTION",
}
